# Generated by Django 5.1.1 on 2024-11-24 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
