# Generated by Django 4.2 on 2024-11-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='user',
            new_name='CustomUser',
        ),
    ]
