# Generated by Django 4.2 on 2024-11-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_rename_user_feedback_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='CustomUser',
            new_name='user',
        ),
    ]
