# Generated by Django 4.2 on 2024-11-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_feedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='gif_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
