# Generated by Django 4.2 on 2024-11-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_comment_parent_comment_alter_response_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
