# Generated by Django 4.2 on 2024-11-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_appointment_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bookable',
            field=models.BooleanField(default=False),
        ),
    ]
