# Generated by Django 5.1.3 on 2024-11-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
