# Generated by Django 4.2 on 2024-12-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_appointmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
