# Generated by Django 4.2 on 2024-12-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_appointment_google_event_id_appointment_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='new_event',
            field=models.BooleanField(default=False),
        ),
    ]
