"""
Django settings for gl_version1 project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path 
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2s8*oex7he=k-+q4(zptzmp5kuoni9fijch*b3d#%87qj2ok98'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# myproject/settings.py
OAUTH2_PROVIDER = {
    'SCOPES': {'calendar': 'Read/write access to Calendar'},
    'CLIENT_ID': 'YOUR CLIENT ID',
    'CLIENT_SECRET': 'YOUR CLIENT_SECRET',
}

GOOGLE_TOKEN_FILE = 'token.json'

GOOGLE_API_SCOPES = ['https://www.googleapis.com/auth/calendar']
GOOGLE_CREDENTIALS_FILE = os.path.join(BASE_DIR, 'credentials.json')
GOOGLE_TOKEN_FILE = os.path.join(BASE_DIR, 'token.json')

# Application definition

INSTALLED_APPS = [
     'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main.apps.MainConfig',
    'crispy_forms',
    'crispy_bootstrap5',
    'tips',
    'EventApp',
    'feedback',
    'forum',
<<<<<<< HEAD
    'base',
=======
    
>>>>>>> main
    'captcha',
    'django.contrib.humanize',
    'counter',
    'mathfilters', 
    'model',
    'chatbot',
    'calendar_integration',
    'oauth2_provider',
    'emotion_detection',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5' 
CRISPY_TEMPLATE_PACK = 'bootstrap5' 

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gl_version1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gl_version1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


import os  # make sure this is at the top of settings.py

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB'),
        'USER': os.environ.get('POSTGRES_USER'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),

    }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static/",
]
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGIN_REDIRECT_URL = '/users/home'

LOGOUT_REDIRECT_URL = '/users/home/'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp-relay.brevo.com'  # Brevo's SMTP server
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = '7d3779003@smtp-brevo.com'  # Your Brevo (Sendinblue) SMTP login
EMAIL_HOST_PASSWORD = 'IM4jdDPYQxCcAL8F'  # Your Brevo SMTP password
DEFAULT_FROM_EMAIL = 'djangotest801@gmail.com'

import os
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')





JAZZMIN_SETTINGS = {
"site_brand": "Dermashield",
"site_title": "Dermashield",
    "site_header": "Dermashield",
"search_model": ["auth.User"],
 #"show_ui_builder": True,
 "site_logo": "777.png",
 "login_logo": "777.png",
 "user_avatar": "profile_picture",
 "site_icon": "777.png",
 "usermenu_links": [
    {"name": "Site", "url": "/", "old_window": False},
],
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-teal",
    "accent": "accent-teal",
    "navbar": "navbar-teal navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-teal",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": False
}

AUTH_USER_MODEL = 'main.CustomUser'


CAPTCHA_FONT_SIZE = 40
CAPTCHA_LENGTH = 6
CAPTCHA_TIMEOUT = 300  # 5 minutes


CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',  # Add your ngrok URL here
]

# STATIC FILES CONFIG FOR PRODUCTION
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # this is your existing folder with media, CSS, etc.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')    # this is where collectstatic dumps everything

# MEDIA FILES
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

